name: 'Update data'

on:
  schedule:
    # During CEST, run daily at 03:00 UTC (i.e. 04:00 during CET or 5:00 CEST).
    - cron: '00 03 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: |
          npm run build
          git config user.name 'Tibia experience history bot'
          git config user.email 'xp-history@tibiamaps.io'
          date=$(date +'%Y-%m-%d')
          git add data README.md
          git commit data README.md -m "Add experience data for date=${date}" || true
          git push
